x = float(input('実数x:'))
y = float(input('実数y:'))
z = float(input('実数z:'))

print(abs(x))
print(bool(x))
print(divmod(x, y))
print(max(x, y))
print(min(x, y))
print(pow(x, y))
print(round(x, 2))
print(round(x, 3))
print(sum((x, y, z)))
